version: '3'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - .env.local

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - postgres
    env_file:
      - .env.local

  redis:
    build: ./compose/redis
