version: '3'

volumes:
  database: {}
  backups: {}
  static: {}
  media: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - database:/var/lib/postgresql/data
      - backups:/backups
    env_file: .env

  django-a:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    ports:
      - "5000"
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  django-b:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    ports:
      - "5000"
    volumes:
      - static:/data/static
      - media:/data/media
    command: /start.sh
    env_file: .env

  django-chroniker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /configure_and_run_cron.sh
    depends_on:
      - postgres
      - redis
    links:
      - postgres
    env_file:
      - .env

  redis:
    build: ./compose/redis
